chore(concept): 638 ContractAgreement admin view
catenax-ng/tx-traceability-foss pull request #1008
Opened 2024-02-22 13:13 UTC by ds-crehm

resolves https://github.com/eclipse-tractusx/traceability-foss/issues/638

2024-02-22 13:49 UTC, mkanal requested changes

2024-02-22 13:49 UTC, mkanal commented on docs/concept/#638-contractagreement-admin-view/contractagreement-datamodel.png
We will not create a new Assets table we will link the Contracts to Assets table this should be clear within this concept. Reference to domain model -> https://eclipse-tractusx.github.io/traceability-foss/docs/arc42/full.html#_domain_concepts

2024-02-22 13:49 UTC, mkanal commented on docs/concept/#638-contractagreement-admin-view/contractagreement-datamodel.puml
see comment above - we could use the https://eclipse-tractusx.github.io/traceability-foss/docs/arc42/full.html#_domain_concepts

2024-02-22 15:00 UTC, ds-crehm commented on docs/concept/#638-contractagreement-admin-view/contractagreement-datamodel.png
Since it was decided to not use the data model for now, I have deleted it from the concept. I have added that information to the chapter out-of-scope, in case it is considered in the future.

2024-02-22 15:00 UTC, ds-crehm commented on docs/concept/#638-contractagreement-admin-view/contractagreement-datamodel.puml
see above

2024-02-28 09:01 UTC, ds-mwesener commented on docs/concept/#638-contractagreement-admin-view/get-all-contracts-sequenceflow.png
The edc client library is not a service. Therefore it cannot be called and should not be part of that sequence diagram. The service is the EDC itself.

2024-02-28 09:03 UTC, ds-mwesener commented on docs/concept/#638-contractagreement-admin-view/get-contract-sequenceflow.png
Same applies here.

2024-02-28 09:03 UTC, ds-mwesener submitted a review, later dismissed
Please fix diagrams.

2024-02-28 10:56 UTC, ds-crehm commented on docs/concept/#638-contractagreement-admin-view/get-all-contracts-sequenceflow.png
Changed it accordingly.

2024-02-28 10:56 UTC, ds-crehm commented on docs/concept/#638-contractagreement-admin-view/get-contract-sequenceflow.png
Changed it accordingly.

2024-02-28 10:59 UTC, ds-mwesener approved these changes

2024-02-28 11:54 UTC, ds-mwesener approved these changes

2024-02-28 11:54 UTC, merged