feature(tx-backend): #536 draft subsequential flow
catenax-ng/tx-traceability-foss pull request #1023
Opened 2024-03-01 07:28 UTC by ds-ext-sceronik

2024-03-11 07:42 UTC, ds-mwesener commented on tx-backend/src/main/resources/application.yml
> +  parts-provider-edc-controlplane-url: ${EDC_PARTS_PROVIDER_CONTROLPLANE_URL:https://provider-edc-controlplane.net}
Add provider-edc-dataplane-url: ${EDC_PROVIDER_DATAPLANE_URL}

2024-03-13 14:26 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/importpoc/PublishService.java
> +    void publishAssetsToCx(List<AssetBase> assets);
```suggestion
    void publishAssetsToCoreServices(List<AssetBase> assets);
```

2024-03-13 14:28 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/model/ImportNote.java
> +    public static final String PUBLISHED_TO_CX = "Assets Pubilshed to network";
```suggestion
    public static final String PUBLISHED_TO_CORE_SERVICES = "Assets Published to network";
```

2024-03-13 14:29 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/model/ImportState.java
> +    PUBLISHED_TO_CX,
```suggestion
    PUBLISHED_TO_CORE_SERVICES,
```

2024-03-13 21:13 UTC, ds-ext-sceronik commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PolicyServiceImpl.java
> +                .orElseThrow(() -> new PolicyNotFoundException("Policy with id: %s not found.".formatted(id)));
The other method is used also in getAllPolicies this one filters by specific assetId and if expected policy is not there then throws exception

2024-03-13 21:14 UTC, ds-ext-sceronik commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
> +        //Publish to CS network
removed comment as method name is descriptive enough :)

2024-03-13 21:22 UTC, ds-ext-sceronik commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ApplicationConfig.java
> +    public EdcAssetService edcDtrAssetService(EdcConfiguration edcConfiguration, EdcTransformer edcTransformer, RestTemplate edcDtrAssetRestTemplate) {
Yep agree. have not considered it in previous implementation. good catch ! for now added EdcConfiguration class that holds all EdcRelated beans that are created from irs-edc-lib :)

2024-03-14 08:22 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/AsyncPublishService.java
> +        List<String> createdShellsAssetIds = new ArrayList<>(List.of());
List.of() can be removed.

2024-03-14 08:23 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/AsyncPublishService.java
> +                    log.error("Failed to create shell in dtr for asset with id %s".formatted(assetBase.getId()), e);
Shouldnt we have some kind of an error somewhere? I only see an log error message.

2024-03-14 08:26 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PolicyServiceImpl.java
> +        return Optional.ofNullable(irsRepository.getPolicies())
emptyIfNull(irsRepository.getPolicies());

2024-03-14 09:37 UTC, ds-mwesener requested changes
Please fix.

2024-03-14 13:57 UTC, merged