Chore/#435 concept show aspect models conntected to aas
catenax-ng/tx-traceability-foss pull request #1025
Opened 2024-03-01 09:43 UTC by mkanal

Trace-X can currently display a defined number of semantic models of the BOMLifecyles asPlanned and asBuilt.
In the future, it can be assumed that further as yet unspecified semantic models will be developed which will also be represented in Trace-X.
Trace-X will be developed to generically handle different existing and planned semantic models.

2024-03-01 10:30 UTC, ds-crehm requested changes

2024-03-01 10:30 UTC, ds-crehm commented on docs/concept/#435-display-aspect-models-connected-to-twin-generic/#435-display-aspect-models-connected-to-twin-generic.md
> +- [ ] Table contains columns "Semantic Model Name" (de: refer to current translation
```suggestion
- [ ] Table contains columns "Semantic Model Name" (de: refer to current translation)
```

2024-03-01 10:30 UTC, ds-crehm commented on docs/concept/#435-display-aspect-models-connected-to-twin-generic/#435-display-aspect-models-connected-to-twin-generic.md
> +- [ ] Table contains columns "Version" of semantic model (de:Version)
```suggestion
- [ ] Table contains columns "Version" of semantic model (de: Version)
```

2024-03-01 10:30 UTC, ds-crehm commented on docs/concept/#435-display-aspect-models-connected-to-twin-generic/#435-display-aspect-models-connected-to-twin-generic.md
> +- [ ] Table contains columns "Semantic Model Id" of semantic model (de:ID Semantisches Modell) /== "Identification" of submodel in IRS response /
```suggestion
- [ ] Table contains columns "Semantic Model Id" of semantic model (de: ID Semantisches Modell) /== "Identification" of submodel in IRS response /
```

2024-03-01 10:30 UTC, ds-crehm commented on docs/concept/#435-display-aspect-models-connected-to-twin-generic/#435-display-aspect-models-connected-to-twin-generic.md
> +- [ ] Viewer Panel has fixed size.
```suggestion
- [ ] Viewer Panel has fixed size
```

2024-03-01 10:30 UTC, ds-crehm commented on docs/concept/#435-display-aspect-models-connected-to-twin-generic/#435-display-aspect-models-connected-to-twin-generic.md
> +- [ ] User selected of Viewer Instance is stored in User Settings. Last selected Viewer Instance will be used for next semantic model selection.
```suggestion
- [ ] User selection of Viewer Instance is stored in User Settings. Last selected Viewer Instance will be used for next semantic model selection.
```

2024-03-01 10:30 UTC, ds-crehm commented on docs/concept/#435-display-aspect-models-connected-to-twin-generic/#435-display-aspect-models-connected-to-twin-generic.md
> +- [ ] Detail View must  be scrollable with vertical scrollbar
Why is this necessary? The information shown in Manufacturer Data, PartSite Information and AssetState is fixed. Only the new Semantic Models table can have information that can expand below the bottom of the view. Would be enough if only that table is scrollable.
```suggestion

```

2024-03-01 10:30 UTC, ds-crehm commented on docs/concept/#435-display-aspect-models-connected-to-twin-generic/#435-display-aspect-models-connected-to-twin-generic.md
> +- [ ] Table with vertical and horizontal scrollbar (No pagination)
Is horizontal scrolling necessary? The amount of columns and the column width is fixed, so the table can't expand horizontally.
```suggestion
- [ ] Table with vertical scrollbar (No pagination)
```

2024-03-01 10:30 UTC, ds-crehm commented on docs/concept/#435-display-aspect-models-connected-to-twin-generic/#435-display-aspect-models-connected-to-twin-generic.md
> +There are further aspect models as the once currently known (SerialPart, Batch, JiS, PartAsPlanned, PartSiteInformation) in the two BomLifecycle asPlanned and asBuilt which are currently implemented
```suggestion
There are further aspect models as the ones currently known (SerialPart, Batch, JiS, PartAsPlanned, PartSiteInformation) in the two BomLifecycle asPlanned and asBuilt which are currently implemented and will be relevant in the future.
```

2024-03-01 10:30 UTC, ds-crehm commented on docs/concept/#435-display-aspect-models-connected-to-twin-generic/#435-display-aspect-models-connected-to-twin-generic.md
> +
Requirements for BE are missing. Copied from [#711](https://github.com/eclipse-tractusx/traceability-foss/issues/711)
```suggestion
- [ ] API endpoints response bodies are extended with required attributes version and payload for Semantic Model Detail View Panel

```

2024-03-01 10:30 UTC, ds-crehm commented on docs/src/uml-diagrams/arc42/cross-cutting/domain-model/domain-model.puml
> +        semantic-model-id: String (max = 255) /' identification  random id of semantic model '/
```suggestion
        semantic-model-id: String (max = 255) /' identification random id of semantic model '/
```

2024-03-01 14:02 UTC, mkanal commented on docs/concept/#435-display-aspect-models-connected-to-twin-generic/#435-display-aspect-models-connected-to-twin-generic.md
> +- [ ] Table with vertical and horizontal scrollbar (No pagination)
As there is only a small bunch of parameters I defined no horizontal scrollbar. But never mind horizontal scrollbar should be only active in case it is necessary so this works for me.

2024-03-04 08:45 UTC, ds-crehm approved these changes

2024-03-04 08:45 UTC, merged