Feature/420 edc contract api
catenax-ng/tx-traceability-foss pull request #1035
Opened 2024-03-05 15:16 UTC by ds-lcapellino

2024-03-06 09:07 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/mapping/submodel/MapperHelper.java
> +                .orElse("");
Why using empty string?

2024-03-06 09:08 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/semanticdatamodel/SemanticDataModel.java
>      public AssetBase toDomainAsBuilt(List<LocalId> localIds, Map<String, String> shortIds, Owner owner, Map<String,
Is this method still in use?

2024-03-06 09:11 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/application/mapper/ContractFieldMapper.java
> +    private static final Map<String, String> SUPPORTED_ASSETS_AS_BUILT_FILTER_FIELDS = Map.ofEntries(
Please give it appropriate name.

2024-03-06 09:12 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/application/rest/ContractsController.java
> +    private final ContractFieldMapper contractFieldMapper;
From my perspective this should be done within the contractService. I know that other controllers also have the field mapper within the controller, but its wrong.

2024-03-06 09:13 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/application/rest/ContractsController.java
> +        if (CollectionUtils.isEmpty(pageableFilterRequest.getOwnPageable().getSort())) {
Dont reset it to a default. Simply pass the null

2024-03-06 09:15 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/domain/exception/ContractException.java
> +public class ContractException extends RuntimeException {
Add it to the error handling config to make sure that the response of the controller will match with a correct statuscode.

2024-03-06 09:16 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractsRepositoryImpl.java
> +public class ContractsRepositoryImpl implements ContractsRepository {
Hi @ds-lcapellino within concept of this story there is no persistance of contracts within tracex. Please clarify.

2024-03-06 09:18 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractsRepositoryImpl.java
> +        String[] contractAgreementIds = contractAgreementInfoViews.getContent().stream().map(ContractAgreementInfoView::getContractAgreementId).toArray(String[]::new);
Why working with a string array when you later map it to an arraylist?

2024-03-06 09:23 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractsRepositoryImpl.java
> +            Page<ContractAgreementInfoView> contractAgreementInfoViews = contractAgreementInfoViewRepository.findAll(specification, pageable);
What happens if specification is null, since you check if specs are there and otherwise returning null.

2024-03-06 09:31 UTC, ds-mwesener commented on tx-backend/src/main/resources/db/migration/V15__add_contract_agreement_id_to_asset.sql
> +ALTER TABLE assets_as_planned
Please merge v15 and v16.

2024-03-06 09:31 UTC, ds-mwesener requested changes
Please see comments.

2024-03-06 12:02 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/semanticdatamodel/SemanticDataModel.java
>      public AssetBase toDomainAsBuilt(List<LocalId> localIds, Map<String, String> shortIds, Owner owner, Map<String,
No, I'll delete it

2024-03-06 12:31 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractsRepositoryImpl.java
> +public class ContractsRepositoryImpl implements ContractsRepository {
@ds-mwesener there is no persistence of contracts. This repository class is used to get the contract data and call the EDC.

2024-03-06 13:04 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractsRepositoryImpl.java
> +        String[] contractAgreementIds = contractAgreementInfoViews.getContent().stream().map(ContractAgreementInfoView::getContractAgreementId).toArray(String[]::new);
So I can verify if the lists diverge. This is only possible if the lists have the same order. toList(); here returns a immutable list that is not sortable.

2024-03-06 13:11 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractsRepositoryImpl.java
> +            Page<ContractAgreementInfoView> contractAgreementInfoViews = contractAgreementInfoViewRepository.findAll(specification, pageable);
Providing a null value for specification behaves like there is no specification present. We used in one of our other repositories.

2024-03-07 11:56 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfig.java
> +    public ResponseEntity<ErrorResponse> handleImportJobNotFoundException(final ContractException exception) {
Naming

2024-03-07 11:56 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfig.java
> +        return ResponseEntity.status(HttpStatus.NOT_FOUND)
Is this the correct code?

2024-03-07 11:57 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/application/rest/ContractsController.java
> +public class ContractsController {
ContractController

2024-03-07 11:57 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/application/service/ContractsService.java
> +public interface ContractsService {
ContractService

2024-03-07 11:57 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/domain/repository/ContractsRepository.java
> +public interface ContractsRepository {
ContractRepository

2024-03-07 11:58 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/model/ContractAgreementInfoView.java
> +public class ContractAgreementInfoView {
contract_agreement_view

ContractAgreementView

2024-03-07 12:00 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/contracts/infrastructure/repository/ContractsRepositoryImpl.java
> +    private void throwIfListDiverge(List<String> contractAgreementIds, List<EdcContractAgreementsResponse> contractAgreements) {
validateContractAgreements

2024-03-07 12:01 UTC, ds-mwesener requested changes
Please see comments

2024-03-07 12:01 UTC, ds-mwesener commented on CHANGELOG.md
> +- add /contracts api to fetch contract agreement information from EDC for assets
Add github issue number #xxx

2024-03-07 13:18 UTC, merged