chore(concept): #578 integrate feedback
catenax-ng/tx-traceability-foss pull request #1060
Opened 2024-03-13 11:06 UTC by ds-crehm

Changed the concept from "empty" display of null values to "-" display of null values.

2024-03-13 12:55 UTC, mkanal requested changes

2024-03-13 12:55 UTC, mkanal commented on docs/concept/#578-consistent-null-values/#578-consistent-null-values.md
> +When sorting the values, empty ones should be always shown at the top regardless of the sort order.
I think this is not correct. In case of sorting this should be at the top or at the bottom according to sort order. 
Only in case the filter options drop down

2024-03-13 12:55 UTC, mkanal commented on docs/concept/#578-consistent-null-values/null-value-filter.png
(empty field) I would use ( )

2024-03-13 13:55 UTC, ds-crehm commented on docs/concept/#578-consistent-null-values/#578-consistent-null-values.md
> +- [ ] Null values are shown as a hyphen "-" in the frontend.
This is irrelevant since the character will only be a visual indication. I have changed it to 'dash' anyways.

2024-03-13 13:55 UTC, ds-crehm commented on docs/concept/#578-consistent-null-values/#578-consistent-null-values.md
> +- [ ] Empty values can be filtered for. They are shown as "*empty field*" when filtering for them. This option is always shown at the top of the filter/search box regardless of what the user is searc
This is irrelevant since the character will only be a visual indication. I have changed it to 'dash' anyways.

2024-03-13 14:10 UTC, ds-crehm commented on docs/concept/#578-consistent-null-values/null-value-filter.png
I think it's enough without brackets. It's already highlighted by writing in cursive and having a separation to the other values.

2024-03-14 10:26 UTC, ds-crehm commented on docs/concept/#578-consistent-null-values/null-value-filter.png
Feedback from Johannes -> We will display it as "-" instead

2024-03-14 10:30 UTC, mkanal approved these changes

2024-03-14 10:31 UTC, merged