Feature/706 merge alerts and investigations
catenax-ng/tx-traceability-foss pull request #1105
Opened 2024-03-24 01:13 UTC by ds-ext-sceronik

2024-03-25 07:23 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/notification/rest/NotificationController.java
> +    private final BaseRequestFieldMapper fieldMapper;
Could you please move that to the serviceimpl?

2024-03-25 07:27 UTC, ds-mwesener requested changes
Please fix.

2024-03-25 08:26 UTC, ds-ext-sceronik commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/notification/rest/NotificationController.java
> +    private final BaseRequestFieldMapper fieldMapper;
After some more thoughts and conversation with current usage of requestFieldMapper and its construct it is not possible to move it to service layer since it will break clean architecture where domain will know about application layer. structure. 
issue will be tackled at later date with refactoring ( or completly removing request field mapper ) and introducing view or implementation changes in specifications itself

2024-03-26 12:37 UTC, ds-mwesener approved these changes

2024-03-26 12:37 UTC, merged