chore(concept): #849 create concept
catenax-ng/tx-traceability-foss pull request #1207
Opened 2024-04-29 10:41 UTC by ds-crehm

2024-04-29 19:22 UTC, ds-mwesener commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +When editing an alert, only one BPN is shown since alerts to multiple BPNs are separate duplicated alerts. Removing this BPN is not possible.
From my perspective it should not be allowed to edit elements which causing a creation of a new notification.

2024-04-29 19:23 UTC, ds-mwesener commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +#### Alert creation
The last iterations we made sure that there is almost no difference anymore between alerts and investigations. Why do we have different behaviours defined here?

2024-04-30 11:26 UTC, ds-crehm commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +When editing an alert, only one BPN is shown since alerts to multiple BPNs are separate duplicated alerts. Removing this BPN is not possible.
Changed it to not be possible.

2024-04-30 11:28 UTC, ds-crehm commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +#### Alert creation
During the creation of investigations/alerts, there is a different behaviour for the BPN selection. That cannot be changed due to the nature of the use cases. So I described both scenarios, while keeping the process as similar as possible.

2024-05-02 13:18 UTC, ds-mwesener commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +- BPN selection is possibly for alerts.
```suggestion
- BPN selection is only possible for alerts.
```

2024-05-02 13:18 UTC, ds-mwesener commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +  - Autocomplete filter -> Selection shows all matching BPNs (if there are more than 10, this selection is scrollable).
To be discussed.

2024-05-02 13:19 UTC, ds-mwesener commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +  - Selected BPNs are shown as chips that can be removed.
Please link to the story which implements that feature

2024-05-02 13:20 UTC, ds-mwesener commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +
Available parts are additionally filtered by the bpns in the bpn input field.

2024-05-02 13:22 UTC, ds-mwesener commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +When editing notifications, only parts with the identical BPN as the "createdFor" BPN will be shown and the user may not add BPNs manually.
Please describe which fields can be edited.

2024-05-02 13:22 UTC, ds-mwesener requested changes
Please adress comments. Thank you

2024-05-06 09:33 UTC, ds-crehm commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +  - Autocomplete filter -> Selection shows all matching BPNs (if there are more than 10, this selection is scrollable).
Will leave it in the concept for now. If it's not possible, we can either change the concept or directly change the PBIs.

2024-05-06 09:34 UTC, ds-crehm commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +  - Selected BPNs are shown as chips that can be removed.
This should be done in the frontend PBI. It's linked in the ticket description of the concept (#849)

2024-05-06 09:34 UTC, ds-crehm commented on docs/concept/#849-notifications-to-multiple-bpns/#849-notifications-to-multiple-bpns.md
> +
Added this

2024-05-07 16:42 UTC, ds-mwesener approved these changes
Approved, we might think of a data format for the case id.

2024-05-08 08:23 UTC, merged