chore-xxx: added interceptor
catenax-ng/tx-traceability-foss pull request #1218
Opened 2024-05-07 10:26 UTC by ds-ashanmugavel

2024-05-07 12:22 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/IrsClientRestTemplateInterceptor.java
> +public class IrsClientRestTemplateInterceptor implements ClientHttpRequestInterceptor {
```suggestion
public class RequestResponseLoggingInterceptor implements ClientHttpRequestInterceptor {
```

2024-06-14 06:53 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/RequestResponseLoggingInterceptor.java
> +    static Logger LOGGER = LoggerFactory.getLogger(RequestResponseLoggingInterceptor.class);
Remove this line.

2024-06-14 06:54 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/RequestResponseLoggingInterceptor.java
> +            LOGGER.info("Response body: {}", bodys.replaceAll("[\r\n]+", " "));
simply use log.

2024-06-14 06:55 UTC, ds-mwesener requested changes
Fix mentioned things.

2024-06-14 08:12 UTC, ds-mwesener approved these changes

2024-06-14 08:13 UTC, merged