feature(ARC42): TRACEFOSS-1010- Scenario 1: Return all Assets
catenax-ng/tx-traceability-foss pull request #123
Opened 2023-03-29 20:03 UTC by graflmsg

2023-03-30 09:38 UTC, mkanal requested changes

2023-03-30 09:38 UTC, mkanal commented on docs/src/docs/arc42/runtime-view/overall.adoc
> +This section describes the overall flow of the Traceability-FOSS
```suggestion
This section describes the overall flow of the Traceability-FOSS application 
```

2023-03-30 09:38 UTC, mkanal commented on docs/src/uml-diagrams/runtime-view/return-all-assets.puml
> +box "Traceability-FOSS" #LightGrey
Please use Trace-X FOSS application and not Traceability-FOSS

2023-03-30 09:38 UTC, mkanal commented on docs/src/uml-diagrams/runtime-view/return-all-assets.puml
> +TraceabilityApiConsumer -> TraceabilityAPI : GET /assets
```suggestion
TraceXApiConsumer -> TraceXAPI : GET /assets
```

2023-03-30 09:38 UTC, mkanal commented on docs/src/uml-diagrams/runtime-view/return-all-assets.puml
> +activate TraceabilityApiConsumer
Please use Trace-X FOSS application and not Traceability-FOSS

2023-03-30 09:38 UTC, mkanal commented on docs/src/uml-diagrams/runtime-view/return-all-assets.puml
> +TraceabilityAPI <-- AssetsController
TraceXAPI instead of TraceabilityAPI

2023-03-30 09:38 UTC, mkanal commented on docs/src/uml-diagrams/runtime-view/get-specific-information-for-assets.puml
> +JpaAssetsRepository -> Blobstore : success
Is the arrow correct?

2023-03-30 09:39 UTC, mkanal commented on docs/src/uml-diagrams/runtime-view/get-specific-information-for-assets.puml
> +JpaAssetsRepository -> Blobstore : success
I have to check the puml files as well. Please be patient.

2023-03-31 08:06 UTC, ds-mwesener requested changes

2023-03-31 08:36 UTC, ds-mwesener approved these changes

2023-03-31 08:37 UTC, merged