Chore-XXX: Fixed  jsonSchemaTest
catenax-ng/tx-traceability-foss pull request #1282
Opened 2024-06-11 08:10 UTC by ds-ashanmugavel

2024-06-11 11:42 UTC, ds-lcapellino commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/JsonSchemaTest.java
> +        }
Since this is a test, there is no need to throw Exceptions. Maybe use assertNotNull.

2024-06-11 11:42 UTC, ds-lcapellino commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/JsonSchemaTest.java
> +    public void test() throws IOException, URISyntaxException {
Please add an appropriate method name

2024-06-11 11:43 UTC, ds-lcapellino commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/JsonSchemaTest.java
>          List<String> strings = isValid(multipartFile);
Use an appropriate variable name instead of strings

2024-06-14 07:01 UTC, ds-mwesener commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/JsonSchemaTest.java
> +    public void testJsonSchema() {
testLatestJsonSchema

2024-06-14 07:01 UTC, ds-mwesener requested changes
Changelog

2024-06-14 07:59 UTC, ds-mwesener approved these changes

2024-06-14 07:59 UTC, merged