Feature/tracefoss 1340 bpn edc url mapping for notification flow
catenax-ng/tx-traceability-foss pull request #176
Opened 2023-04-18 07:23 UTC by graflmsg

2023-04-18 10:20 UTC, ds-mwesener commented
Please improve code coverage to > 80%

2023-04-18 13:00 UTC, ds-mwesener commented on backend/src/integration/groovy/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcControllerIT.groovy
> +                    .body("content", Matchers.hasSize(1))
Please exact match assert.

2023-04-18 13:01 UTC, ds-mwesener commented on backend/src/integration/groovy/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcControllerIT.groovy
> +        given()
Could you please extract the creation of a bpn with input option into the BpnEdcSupport. Then we would not need to repeat it on other tests.

2023-04-18 13:01 UTC, ds-mwesener commented on backend/src/integration/groovy/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcControllerIT.groovy
> +}
Please also negative test cases. Unauthorized, bad request

2023-04-18 13:40 UTC, ds-mwesener commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcEntity.java
> +public class BpnEdcEntity {
Please add created, updated fields and use prePersist and preUpdate to keep them up to date.

2023-04-19 13:20 UTC, ds-mwesener requested changes
Please rework.

2023-04-19 13:20 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcController.java
> +@RequestMapping(path = "/bpn-config", produces = "application/json", consumes = "application/json")
As you provide a http get request which does not consume application/json you need to configure it on specific api and not controller level.

2023-04-19 13:20 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcController.java
> +    public static boolean validateUrl(String url) {
Remove this unused method. You have already implemented it on custom validator interface

2023-04-19 13:20 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcController.java
> +/********************************************************************************
Still no logging integrated on the valueable spots.

2023-04-19 13:20 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcService.java
> +package org.eclipse.tractusx.traceability.infrastructure.jpa.bpn_edc;
I still do not see any exception handling. Example: Please create exception for domain. Make sure to throw it appropriate and catch it in the global error handler. What if createBpnEdcUrlMapping() retrieves existing bpn? This will be a response of 200 without creation, as current implemented.

2023-04-19 13:20 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcService.java
> +        bpnEdcRepository.deleteById(bpn);
Here a database exception will be thrown. We want our own exceptions.

2023-04-19 13:20 UTC, ds-mwesener commented on tx-backend/src/integration/groovy/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcControllerIT.groovy
> +class BpnEdcControllerIT extends IntegrationSpecification implements BpnRepositoryProvider {
There is still at least a test case missing for bad requests.

2023-04-20 05:48 UTC, graflmsg commented on backend/src/main/resources/db/migration/V15_bpn_edc_url_mapping.sql
> +create table bpn_edc_mappings
All the existing SQL scripts are missing such "if exists" condition. These SQL statements were added chronologically and will always be executed against a clean database (see the integration tests). Makes no sense to force this condition.

2023-04-20 05:48 UTC, graflmsg commented on backend/src/main/resources/db/migration/V15_bpn_edc_url_mapping.sql
> +insert into bpn_edc_mappings values('BPNL00000000BJTL', 'https://trace-x-test-edc.dev.demo.catena-x.net/a1');
All the existing SQL scripts are missing such "if exists" condition. These SQL statements were added chronologically and will always be executed against a clean database (see the integration tests). Makes no sense to force this condition.

2023-04-20 05:48 UTC, graflmsg commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/PersistentBpnEdcRepository.java
> +        Optional<BpnEdcEntity> rv = jpaBpnEdcRepository.findById(bpn);
Solved

2023-04-20 05:49 UTC, graflmsg commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcController.java
> +/********************************************************************************
Log statements added.

2023-04-20 05:49 UTC, graflmsg commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcController.java
> +    private static final Logger LOGGER = LoggerFactory.getLogger(BpnEdcController.class);
Lookup used

2023-04-20 05:51 UTC, graflmsg commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdc.java
> +    public BpnEdc(String bpn, String url) {
Where do we have an already working builder? Would be nice to see one :-)

2023-04-20 05:52 UTC, graflmsg commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/PersistentBpnEdcRepository.java
> +        return new BpnEdc(entity.getBpn(), entity.getUrl());
Right. But, anyway, the return makes no sense, I have removed it.

2023-04-20 05:52 UTC, graflmsg commented on backend/src/integration/groovy/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcControllerIT.groovy
> +                    .body("content", Matchers.hasSize(1))
Extra asserts introduced.

2023-04-20 05:53 UTC, graflmsg commented on backend/src/integration/groovy/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcControllerIT.groovy
> +}
Extra tests introduced.

2023-04-20 05:56 UTC, graflmsg commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcEntity.java
> +public class BpnEdcEntity {
Why do you want to make more complicated a very simple entity? By the way, currently no entity uses such lifecycle events. Or?

2023-04-20 06:01 UTC, graflmsg commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcController.java
> +@RequestMapping(path = "/bpn-config", produces = "application/json", consumes = "application/json")
Is it only this new controller in this situation?

2023-04-20 06:01 UTC, graflmsg commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcController.java
> +    public static boolean validateUrl(String url) {
Method removed.

2023-04-20 06:02 UTC, graflmsg commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcController.java
> +/********************************************************************************
Log statements added.

2023-04-20 06:11 UTC, graflmsg commented on tx-backend/src/integration/groovy/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcControllerIT.groovy
> +class BpnEdcControllerIT extends IntegrationSpecification implements BpnRepositoryProvider {
Two more tests introduced: 
"should report a bad request" and "should report an unauthorized request"

2023-04-20 14:25 UTC, ds-mwesener requested changes
Please rework.

2023-04-20 14:25 UTC, ds-mwesener commented on tx-backend/src/integration/groovy/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcControllerIT.groovy
> +class BpnEdcControllerIT extends IntegrationSpecification implements BpnRepositoryProvider {
Bad request is still not implemented. You verify 500 instead of 400.

2023-04-20 14:25 UTC, ds-mwesener commented on tx-backend/src/integration/groovy/org/eclipse/tractusx/traceability/common/support/BpnEdcRepositoryProvider.groovy
> +/********************************************************************************
This file is new, so remove BMW and ZF from the header.

2023-04-20 14:25 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcService.java
> +        bpnEdcRepository.deleteById(bpn);
Still not adressed.

2023-04-20 14:26 UTC, ds-mwesener commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdc.java
> +    public BpnEdc(String bpn, String url) {
Hi almost all classes within the blackbox use builders already. But as we should make sure to get this done, please do not implement it now.

2023-04-20 14:28 UTC, ds-mwesener requested changes

2023-04-21 07:02 UTC, graflmsg commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcController.java
> +public class BpnEdcController {
It has already this annotation

2023-04-21 07:05 UTC, graflmsg commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcRequest.java
> +    @NotNull(message = "A valid URL must be present") String url
See the ValidUrlParameter interface

2023-04-21 07:13 UTC, graflmsg commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcController.java
> +    public void createBpnEdcUrlMappings(@Valid @RequestBody BpnEdcRequest request) {
Renamed

2023-04-21 07:14 UTC, graflmsg commented on backend/src/main/java/org/eclipse/tractusx/traceability/infrastructure/jpa/bpn_edc/BpnEdcResponse.java
> +        @ApiModelProperty(example = "https://trace-x-test-edc.dev.demo.catena-x.net/a1") List<String> urls) {
Not used anymore, removed

2023-04-28 20:21 UTC, ds-mwesener approved these changes

2023-04-28 20:23 UTC, merged