Chore/tracefoss 1376 asset refactoring and tests
catenax-ng/tx-traceability-foss pull request #253
Opened 2023-05-10 15:08 UTC by ds-ext-sceronik

2023-05-15 09:14 UTC, ds-mwesener commented on tx-backend/openapi/traceability-foss-backend.json
> ~                "schema": {
rollback file please

2023-05-15 09:15 UTC, ds-mwesener commented on tx-backend/src/integration/groovy/org/eclipse/tractusx/traceability/assets/infrastructure/rest/EDCReceiverController.java
>  @RequestMapping("/edc/")
@Slf4j then the logger can be removed.

2023-05-15 09:16 UTC, ds-mwesener commented on tx-backend/src/integration/groovy/org/eclipse/tractusx/traceability/assets/infrastructure/rest/EDCReceiverController.java
> +					.property(ASSET_KEY_NOTIFICATION_TYPE, Asset.ASSET_VALUE_QUALITY_INVESTIGATION)
Why is the second value in Asset and the first one not?

2023-05-15 09:17 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/rest/response/AssetResponse.java
> + * Copyright (c) 2022, 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
License Header as described please

2023-05-15 09:18 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/rest/response/AssetResponse.java
> +    public record DescriptionsResponse(
Better in own class?

2023-05-15 09:19 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/rest/response/QualityTypeRequestResponse.java
> + * Copyright (c) 2022, 2023 Bayerische Motoren Werke Aktiengesellschaft (BMW AG)
License header.

2023-05-15 09:24 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/rest/response/QualityTypeRequestResponse.java
> +public enum QualityTypeRequestResponse {
I would duplicate it if it is a request and a response? What do you think?

2023-05-15 09:27 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/feign/irs/model/IrsOwner.java
> +public enum IrsOwner {
I would not name it IrsOwner as the Owner will be created within tracex and has nothing to do with irs. It will be created based on the bpn and the relations between assets.

2023-05-15 09:29 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/jpa/asset/PersistentAssetsRepository.java
> +import org.eclipse.tractusx.traceability.assets.domain.service.repository.AssetRepository;
I guess you draw a line on that point because the mappers are still in this class. Ok for me.

2023-05-15 09:33 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/bpn/mapping/infrastructure/adapters/jpa/BpnEdcMappingEntity.java
> +@AllArgsConstructor
Remove all args constructor

2023-05-15 09:33 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/bpn/mapping/infrastructure/adapters/jpa/PersistentBpnEdcMappingRepository.java
>      public BpnEdcMapping findById(String bpn) {
Might be good to call that method: findByIdOrThrowNotFoundException

2023-05-15 09:38 UTC, ds-mwesener commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/feign/irs/model/IrsOwnerTest.java
> +package org.eclipse.tractusx.traceability.assets.infrastructure.adapters.feign.irs.model;
Missing license header

2023-05-15 09:38 UTC, ds-mwesener commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/application/rest/RegistryControllerTest.java
> +/********************************************************************************
License header

2023-05-15 09:38 UTC, ds-mwesener commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/jpa/shelldescriptor/ShellDescriptorEntityTest.java
> +/********************************************************************************
License

2023-05-15 09:39 UTC, ds-mwesener commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/infrastructure/edc/blackbox/negotiation/ContractNegotiationStatesTest.java
> +/********************************************************************************
License

2023-05-15 09:44 UTC, ds-ext-sceronik commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/application/rest/response/QualityTypeRequestResponse.java
> +public enum QualityTypeRequestResponse {
Yes I will do that . I thought about splitting it but then I thought it is used in both places the same way so I holded up. 
to keep proper architecture it will be required though

2023-05-15 09:59 UTC, ds-ext-sceronik commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/jpa/asset/PersistentAssetsRepository.java
> +import org.eclipse.tractusx.traceability.assets.domain.service.repository.AssetRepository;
Indeed . I would love to continue it in with future tasks at much smaller paste that this MergeRequest ^^

2023-05-15 10:04 UTC, ds-ext-sceronik commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/jpa/metrics/registrylookup/RegistryLookupMetricEntity.java
> +@AllArgsConstructor
You are right . AllArgsConstructor is not needed in this case. not used in code and JPA does not need this constructor due to fact that it is using setters to manage entities :)

2023-05-15 10:13 UTC, ds-ext-sceronik commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/bpn/mapping/infrastructure/adapters/jpa/BpnEdcMappingEntity.java
> +@AllArgsConstructor
it is used in @Builder annotation

2023-05-15 10:17 UTC, ds-ext-sceronik commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/bpn/mapping/infrastructure/adapters/jpa/PersistentBpnEdcMappingRepository.java
>      public BpnEdcMapping findById(String bpn) {
will do that . although I have a question on handling repository methods handling :)

2023-05-15 13:22 UTC, ds-ext-sceronik commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/adapters/feign/irs/model/IrsOwner.java
> +public enum IrsOwner {
Clarified. Missunderstood usage of Owner in here :)

2023-05-15 13:33 UTC, ds-ext-sceronik commented on tx-models/pom.xml
> +    <dependencies>
removed dependencies for now untill we start to move to that module since I imported some libs that might be no longer needed after we agree to move to final architecture solution ( with mappers on tx-backend)

2023-05-15 19:33 UTC, ds-mwesener requested changes
Hi @ds-ext-sceronik code seems to be fine now. Thank you very much. 
I will approve after we have verified the logic on our dev environment. Please schedule a meeting with me.

2023-05-15 19:35 UTC, ds-mwesener requested changes
One more thing, please add a changelog entry which reflects your changes.

2023-05-22 10:51 UTC, ds-mwesener approved these changes
LGTM

2023-05-22 10:51 UTC, merged