feature: TRACEFOSS-1111 update spring profiles on e2e env.
catenax-ng/tx-traceability-foss pull request #257
Opened 2023-05-14 18:18 UTC by ds-mwesener

2023-05-15 19:17 UTC, ds-mwesener commented
Hi please ignore the frontend changes - I rebased and therefore there will be shown as changed but this is not correct. If you check diff from main you will not see those changes. Seems to be a github ui bug.

2023-05-16 07:27 UTC, ds-mmaul requested changes

2023-05-16 07:27 UTC, ds-mmaul commented on CHANGELOG.md
> +- E2E B env profile configuration
"E2E Trace-X A and B profile configuration" - suggestion to summarize those two points into one

2023-05-16 07:27 UTC, ds-mmaul commented on CHANGELOG.md
> +- Bump asciidoctorj from 2.5.7 to 2.5.8
Maybe summarize bumps?

2023-05-16 07:27 UTC, ds-mmaul commented on CHANGELOG.md
> +- Refactored other-parts.component.html - split into new components: supplier-parts.component.html and customer-parts.component.html
Less detail (exact file names) → explanation of the change

2023-05-16 07:27 UTC, ds-mmaul commented on tx-backend/src/main/resources/application-e2e-a.yml
> +# Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
when new files get created --> only eclipse Copyright header + this year (delete 2022)

2023-05-16 07:27 UTC, ds-mmaul commented on tx-backend/src/main/resources/application-e2e-b.yml
> +# Copyright (c) 2022, 2023 Contributors to the Eclipse Foundation
when new files get created --> only eclipse Copyright header + this year (delete 2022)

2023-05-16 07:38 UTC, ds-mwesener commented on CHANGELOG.md
> +- Refactored other-parts.component.html - split into new components: supplier-parts.component.html and customer-parts.component.html
Hi Martin, this is already merged to main and to eclipse. Was not my part so I would like to not change it.

2023-05-16 07:46 UTC, ds-mwesener commented on CHANGELOG.md
> +- Bump asciidoctorj from 2.5.7 to 2.5.8
I would like to have them line by line because every update is independend from each other.

2023-05-16 07:47 UTC, ds-mwesener commented on CHANGELOG.md
> +- E2E B env profile configuration
Addressed.

2023-05-16 07:48 UTC, ds-mwesener reviewed
Thanks everything has been adressed.

2023-05-16 07:56 UTC, ds-mmaul approved these changes
LGTM

2023-05-16 08:01 UTC, merged