Feature/tracefoss 1393 quality alerts api
catenax-ng/tx-traceability-foss pull request #268
Opened 2023-05-22 20:58 UTC by ds-ext-sceronik

- added api for alerts 
- updated insomnia collection with new endpoints

2023-05-23 13:30 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/qualitynotification/application/request/StartQualityNotificationRequest.java
>      @ValidSeverity
Can we get rid of the ValidSeverity and use the JsonCreator approach for handling the exception / validation?

2023-05-23 13:32 UTC, ds-mwesener commented on tx-backend/collection/Insomnia_2023-05-22_deprecated.json
> +{
I have already refactored the collection to include private environments. Can we maybe merge that not on that pull request here? Otherwise I would need to redo everything. On your side it should only be a folder probably?

2023-05-23 13:33 UTC, ds-mwesener commented
> [**TX Backend**] Kudos, SonarCloud Quality Gate passed!    [![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)](https://sonarcloud.io/dashboard?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=CODE_SMELL) [3 Code Smells](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&resolved=false&types=CODE_SMELL)
> 
> [![89.4%](https://camo.githubusercontent.com/86b73734925524d51d47145ab1a1d3d06233748f7a9b0f77993d531ce5110d8e/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f36302d313670782e706e67)](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&metric=new_coverage&view=list) [89.4% Coverage](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_backend&pullRequest=268&metric=new_duplicated_lines_density&view=list)

Code smells are okay on that point. Only for a short time until service is implemented.

2023-05-24 13:32 UTC, ds-mwesener commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/qualitynotification/application/request/QualityNotificationSeverityRequestTest.java
> +        assertThrows(ValueInstantiationException.class, () -> objectMapper.readValue(input, QualityNotificationSeverityRequest.class));
Hi, why is there not a NoSuchElementException thrown? It doesnt seems like we have full control over the exception so far.

2023-05-24 13:33 UTC, ds-mwesener requested changes
Please rework.

2023-05-24 17:47 UTC, ds-ext-sceronik commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/qualitynotification/application/request/QualityNotificationSeverityRequestTest.java
> +        assertThrows(ValueInstantiationException.class, () -> objectMapper.readValue(input, QualityNotificationSeverityRequest.class));
It is thrown as root cause since this is wrapped in ValueInstantiationException. 
when there is a rest call NoSuchElementException is wrapped in HttpMessageNotReadableException. 
what we could do in this case is to test if thrown exception root cause is NoSuchElementException.

2023-05-24 18:08 UTC, ds-ext-sceronik commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/qualitynotification/domain/service/InvestigationServiceImplTest.java
not sure if I understand. there is no more logic in service to create severity from passed string paramether. 
I have created new enum severity request so method to domain is handling mapping to domain severity

2023-05-27 19:10 UTC, ds-mwesener approved these changes
Seems good for me now. Thanks for your rework!

In future we need to structure the integration tests to have a better overview - for now okay for me.

2023-05-28 18:49 UTC, merged