feature: TRACEFOSS-2566 Batch 2.0.0 support
catenax-ng/tx-traceability-foss pull request #520
Opened 2023-08-24 11:38 UTC by ds-ext-sceronik

2023-09-07 06:11 UTC, mkanal requested changes

2023-09-07 06:11 UTC, mkanal commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server.dev.demo.catena-x.net -edc https://trace-x-edc.dev.demo.catena-x.net -a https://trace-x-regis
Please do not use concrete BPN as the BPNS are not known in the tractus-x env. use parameter like the <apiKey> [bpn,...]

2023-09-07 06:11 UTC, mkanal commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server-test.dev.demo.catena-x.net -edc https://trace-x-test-edc.dev.demo.catena-x.net -a https://tra
Please do not use concrete BPN as the BPNS are not known in the tractus-x env. use parameter like the <apiKey> [bpn,...]

2023-09-07 06:11 UTC, mkanal commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server-e2e-a.dev.demo.catena-x.net -edc https://trace-x-edc-e2e-a.dev.demo.catena-x.net -a https://t
Please do not use concrete BPN as the BPNS are not known in the tractus-x env. use parameter like the <apiKey> [bpn,...]

2023-09-07 06:11 UTC, mkanal commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server-e2e-b.dev.demo.catena-x.net -edc https://trace-x-edc-e2e-b.dev.demo.catena-x.net -a https://t
Please do not use concrete BPN as the BPNS are not known in the tractus-x env. use parameter like the <apiKey> [bpn,...]

2023-09-07 06:11 UTC, mkanal commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server-int-a.int.demo.catena-x.net -edc https://trace-x-edc-int-a.int.demo.catena-x.net -a https://t
Please do not use concrete BPN as the BPNS are not known in the tractus-x env. use parameter like the <apiKey> [bpn,...]

2023-09-07 06:11 UTC, mkanal commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server-int-b.int.demo.catena-x.net -edc https://trace-x-edc-int-b.int.demo.catena-x.net -a https://t
Please do not use concrete BPN as the BPNS are not known in the tractus-x env. use parameter like the <apiKey> [bpn,...]

2023-09-07 06:11 UTC, mkanal commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/repository/rest/irs/model/JobDetailResponseTest.java
> +                        Objects.equals(asset.getSemanticModel().getNameAtCustomer(), "--")
What is "--" is this the default mapping then we have to change that.

2023-09-07 06:11 UTC, mkanal commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/repository/rest/irs/model/JobDetailResponseTest.java
> +                                && Objects.equals(asset.getSemanticModel().getCustomerPartId(), "--"));
What is "--" is this the default mapping then we have to change that.

2023-09-07 06:11 UTC, mkanal commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/repository/rest/irs/model/JobDetailResponseTest.java
> +    @Test
Only a single test?

2023-09-07 06:11 UTC, mkanal commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/repository/rest/irs/model/JobDetailResponseTest.java
> +                                && Objects.equals(asset.getSemanticModel().getCustomerPartId(), "--"));
"nameAtManufacturer": "Door Key" is this not the testdata yoiu are using?

2023-09-07 06:20 UTC, ds-ext-sceronik commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server.dev.demo.catena-x.net -edc https://trace-x-edc.dev.demo.catena-x.net -a https://trace-x-regis
These script invocations are for specific environments and specific test dataset that have provided BPNs so we know BPNs for that envs. 
Also please consider additionaly that these invocations are developer specific support resetting development environment.

2023-09-07 06:20 UTC, ds-ext-sceronik commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server-test.dev.demo.catena-x.net -edc https://trace-x-test-edc.dev.demo.catena-x.net -a https://tra
same as above

2023-09-07 06:20 UTC, ds-ext-sceronik commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server-e2e-b.dev.demo.catena-x.net -edc https://trace-x-edc-e2e-b.dev.demo.catena-x.net -a https://t
same as above

2023-09-07 06:20 UTC, ds-ext-sceronik commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server-e2e-a.dev.demo.catena-x.net -edc https://trace-x-edc-e2e-a.dev.demo.catena-x.net -a https://t
same as above

2023-09-07 06:21 UTC, ds-ext-sceronik commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server-int-a.int.demo.catena-x.net -edc https://trace-x-edc-int-a.int.demo.catena-x.net -a https://t
same as above

2023-09-07 06:21 UTC, ds-ext-sceronik commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server-int-b.int.demo.catena-x.net -edc https://trace-x-edc-int-b.int.demo.catena-x.net -a https://t
same as above

2023-09-07 06:23 UTC, ds-ext-sceronik commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/repository/rest/irs/model/JobDetailResponseTest.java
> +                        Objects.equals(asset.getSemanticModel().getNameAtCustomer(), "--")
this is already implemented mapping behaviour so I have not changed that I am just testing that it is behaving as implemented. there are much more fields that behave this way if field is not provided ( null from IRS job response ) 
What mapping should be used here if none is provided ?

2023-09-07 06:39 UTC, ds-ext-sceronik commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/repository/rest/irs/model/JobDetailResponseTest.java
> +    @Test
no more tests required in this case. this for a confirmation that our mapper is able to deserialize specific job response from IRS. 
As it was suggested on Developers meeting we should test it additionaly with our dataset after deploying and cleaning up environment since this is provided by IRS response we cannot be guessing here what possible outcomes will be in response from dependant service.

2023-09-08 08:58 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/shelldescriptor/application/RegistryController.java
> +
please remove this line

2023-09-08 09:02 UTC, ds-lcapellino commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/assets/infrastructure/repository/rest/irs/model/JobDetailResponseTest.java
> +        val assets = response.convertAssets();
you used lombok.val here did you mean to use java var?

2023-09-08 09:05 UTC, ds-lcapellino commented on dev/README.md
> +python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7.json -s https://tracex-submodel-server.dev.demo.catena-x.net -edc https://trace-x-edc.dev.demo.catena-x.net -a https://trace-x-regis
```suggestion
python transform-and-upload.py -f CX_Testdata_MessagingTest_v0.0.7_with_batch_v2.0.0.json -s https://tracex-submodel-server.dev.demo.catena-x.net -edc https://trace-x-edc.dev.demo.catena-x.net -a https://trace-x-registry.dev.demo.catena-x.net/semantics/registry/api/v3.0 -d https://trace-x-edc-dataplane.dev.demo.catena-x.net -p id-3.0-trace -k <apiKey> --aas3 --allowedBPNs BPNL00000003CML1 BPNL00000003CNKC
```

2023-09-08 10:26 UTC, ds-lcapellino approved these changes
LGTM

2023-09-08 10:27 UTC, merged