TRACEFOSS-1065 - [FE] User select severity for Quality Investigation
catenax-ng/tx-traceability-foss pull request #56
Opened 2023-03-13 07:14 UTC by ds-ext-dskrzypczak

TRACEFOSS-1065

2023-03-13 08:03 UTC, evia-fbedarf requested changes

2023-03-13 08:03 UTC, evia-fbedarf commented on frontend/src/app/modules/shared/model/severity.model.ts
> +  MINOR = 'MINOR',
This would be also a candidate for the severity module we could create.

2023-03-13 08:03 UTC, evia-fbedarf commented on frontend/src/app/modules/shared/modules/notification/notification-tab/notification-tab.component.ts
> +      'severity',
This is a notification component. So it should not contain anything only related to investigations alone.

I don't know if severity will be a feature of alerts, that is why we should keep it as an optional field.
Maybe take a look at my PR. #35 I tackled this issue there

2023-03-13 13:44 UTC, ds-ext-dskrzypczak commented on frontend/src/app/modules/shared/modules/notification/notification-tab/notification-tab.component.ts
> +      'severity',
I moved 'severity' to "optionalColumns" even though it seems to also be a part of Quality Alerts. But let's leave it as it's now, Thomas is ok with putting 'severity' as the last column.

2023-03-14 15:40 UTC, ds-ext-dskrzypczak commented on frontend/src/app/modules/shared/model/severity.model.ts
> +  MINOR = 'MINOR',
So far I decided to leave it as it is, because of problems with separated SeverityModule (here is more about problems: https://github.com/catenax-ng/tx-traceability-foss/pull/56#discussion_r1135758231 )

2023-03-15 11:34 UTC, graflmsg approved these changes
OK, looks good

2023-03-15 12:03 UTC, merged