environment TRACEFOSS-2373 stable environments preparation
catenax-ng/tx-traceability-foss pull request #602
Opened 2023-09-21 14:12 UTC by ds-ext-sceronik

2023-09-22 05:28 UTC, ds-mwesener requested changes
Questions: 
Do we also need to provide data? If yes we would need an edc provider.

2023-09-22 05:29 UTC, ds-mwesener commented on charts/connector/aasregistry/values-stable-a.yaml
> +    host: trace-x-registry-stable-a.stable.demo.catena-x.net
Want to go with tx-registry? To follow our new naming model. This has not been changed on the other environments so far. What do you think?

2023-09-22 05:29 UTC, ds-mwesener commented on charts/connector/submodelservers/values-stable-a.yaml
> +    - host: "tracex-submodel-server-stable-a.stable.demo.catena-x.net"
Here as well? tx-submodel-server...

2023-09-22 05:29 UTC, ds-mwesener commented on charts/connector/submodelservers/values-stable-a.yaml
> +        - "tracex-submodel-server-stable-a.stable.demo.catena-x.net"
.

2023-09-22 05:30 UTC, ds-mwesener commented on charts/connector/submodelservers/values-stable-b.yaml
> +    - host: "tracex-submodel-server-stable-b.stable.demo.catena-x.net"
.

2023-09-22 05:30 UTC, ds-mwesener commented on charts/connector/submodelservers/values-stable-b.yaml
> +        - "tracex-submodel-server-stable-b.stable.demo.catena-x.net"
.

2023-09-22 05:31 UTC, ds-mwesener commented on charts/traceability-foss/values-stable-a.yaml
> +  springprofile: stable
As we will not have specific profiles anymore this should be dev right?

2023-09-22 05:32 UTC, ds-mwesener commented on charts/traceability-foss/values-stable-a.yaml
> +    urlWithPath: "https://trace-x-registry-stable-a.stable.demo.catena-x.net/semantics/registry/api/v3.0"
If we change - please also change here.

2023-09-22 05:36 UTC, ds-mwesener commented on charts/traceability-foss/values-stable-a.yaml
> +    url: "https://traceability-stable-a.stable.demo.catena-x.net"
Should be tx- not traceability?

2023-09-22 06:58 UTC, ds-ext-sceronik commented on charts/traceability-foss/values-stable-a.yaml
> +  springprofile: stable
will keep only dev

2023-09-25 06:34 UTC, ds-mwesener commented on charts/connector/edc-provider/values-stable-a.yaml
> +    httpProxyTokenReceiverUrl: "https://traceability-stable-a.stable.demo.catena-x.net/api/callback/endpoint-data-reference"
Should be the backend url, correct?

2023-09-25 06:35 UTC, ds-mwesener commented on charts/connector/edc-provider/values-stable-b.yaml
> +    httpProxyTokenReceiverUrl: "https://traceability-stable-b.stable.demo.catena-x.net/api/callback/endpoint-data-reference"
Should be the backend url.

2023-09-25 06:36 UTC, ds-mwesener commented on charts/connector/submodelservers/values-stable-a.yaml
> +  # targetMemoryUtilizationPercentage: 80
Remove comment

2023-09-25 06:38 UTC, ds-mwesener approved these changes

2023-09-25 07:00 UTC, merged