Feature/tracefoss 2512 global search
catenax-ng/tx-traceability-foss pull request #636
Opened 2023-10-04 05:54 UTC by ds-mwesener

2023-10-04 18:12 UTC, ds-ext-sceronik approved these changes
LGTM :)

2023-10-05 11:20 UTC, ds-mmaul requested changes

2023-10-05 11:20 UTC, ds-mmaul commented on frontend/src/app/modules/page/parts/presentation/parts.component.ts
> +        });
delete this

2023-10-05 11:20 UTC, ds-mmaul commented on frontend/src/app/modules/page/parts/presentation/parts.component.ts
> +            if (partTableComponent.multiCompo.theSearchElement) {
maybe consider rename of multicompo

2023-10-05 11:20 UTC, ds-mmaul commented on frontend/src/app/modules/shared/components/multi-select-autocomplete/multi-select-autocomplete.component.ts
> +        console.log("selection change");
delete

2023-10-05 11:21 UTC, ds-mmaul commented
> [**Trace-X Root**] Kudos, SonarCloud Quality Gate passed!    [![Quality Gate passed](https://camo.githubusercontent.com/e4a90cf346b46d44c5652111d68603714bfb7693043d07a95992de3a30bfce04/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f5175616c6974794761746542616467652f7061737365642d313670782e706e67)](https://sonarcloud.io/dashboard?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636)
> 
> [![Bug](https://camo.githubusercontent.com/4c6102327f5a954f9c8acaf2e2714183157a9e41717b371b2cd585cf25057310/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f6275672d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=BUG) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=BUG) [0 Bugs](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=BUG) [![Vulnerability](https://camo.githubusercontent.com/3ba1ee49636ffc3427e38649a9f8a65ee392f28e8a662fcf96ce24cefbb520e9/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f76756c6e65726162696c6974792d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=VULNERABILITY) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=VULNERABILITY) [0 Vulnerabilities](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=VULNERABILITY) [![Security Hotspot](https://camo.githubusercontent.com/fb735cbe76f8d5e1679c76ce83b740ceb1eaf62de4f7bf88623dc9953261aff7/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f73656375726974795f686f7473706f742d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=SECURITY_HOTSPOT) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=SECURITY_HOTSPOT) [0 Security Hotspots](https://sonarcloud.io/project/security_hotspots?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=SECURITY_HOTSPOT) [![Code Smell](https://camo.githubusercontent.com/8fe18b2dfb6f7d4e44582f281b29f617eb5ae07c248d2002ca586e91da219212/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636f6d6d6f6e2f636f64655f736d656c6c2d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=CODE_SMELL) [![A](https://camo.githubusercontent.com/1cba125a897d7fa47033a3b3b2be2bbee680d34d4f004a215564659b853fb201/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f526174696e6742616467652f412d313670782e706e67)](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=CODE_SMELL) [5 Code Smells](https://sonarcloud.io/project/issues?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&resolved=false&types=CODE_SMELL)
> 
> [![88.7%](https://camo.githubusercontent.com/86b73734925524d51d47145ab1a1d3d06233748f7a9b0f77993d531ce5110d8e/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f436f76657261676543686172742f36302d313670782e706e67)](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&metric=new_coverage&view=list) [88.7% Coverage](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&metric=new_coverage&view=list) [![0.0%](https://camo.githubusercontent.com/8047c63e1f9ed03f63001e1eadce4676bade3e0f83ec690a9c625287796248a6/68747470733a2f2f736f6e6172736f757263652e6769746875622e696f2f736f6e6172636c6f75642d6769746875622d7374617469632d7265736f75726365732f76322f636865636b732f4475706c69636174696f6e732f332d313670782e706e67)](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&metric=new_duplicated_lines_density&view=list) [0.0% Duplication](https://sonarcloud.io/component_measures?id=catenax-ng_tx-traceability-foss_backend&pullRequest=636&metric=new_duplicated_lines_density&view=list)

check code smells

2023-10-05 11:37 UTC, ds-mmaul approved these changes
LGTM

2023-10-05 11:40 UTC, merged