chore: [TRACEFOSS-XXX] added compatibility matrix as md file
catenax-ng/tx-traceability-foss pull request #710
Opened 2023-10-27 08:20 UTC by ds-jleyh

Added new md file with compatibility matrix for services.
Contents may need to be revised.

2023-10-27 08:44 UTC, ds-mwesener commented on COMPATIBILITY_MATRIX.md
> +# Compatibility matrix
Hi @ds-jleyh could you please check how we want to deal with versions in the future. I think it will not be good to have everything in one document. Instead we could think about using version tags in the filename or something similiar?

2023-10-27 08:45 UTC, ds-mwesener commented on COMPATIBILITY_MATRIX.md
> +| frontend             | 1.3.14  | 2023-10-26            |                        |
Trace-X Version 1.3.14 consists of frontend & backend so there is no need to add them as dependency.

2023-10-27 08:46 UTC, ds-mwesener commented on COMPATIBILITY_MATRIX.md
> +| postgresql           | 12.1.6  | 2023-10-26            | alias: edc-postgresql  |
That this postgres is related to the edc should be somewhere but not in the comment section. Because it will be always like that. Please add that to the name.

2023-10-27 08:46 UTC, ds-mwesener commented on COMPATIBILITY_MATRIX.md
> +
I am not sure if the date brings any necessary info with it. What do you think

2023-10-27 08:47 UTC, ds-mwesener commented on COMPATIBILITY_MATRIX.md
> +## Registry version 0.0.1
We are not resposible for maintaining the compatiblity to the registry. We want to make sure that our application works with a specific registry version. Please remove the section and add the registry with a specific version to the trace-x application

2023-10-27 08:48 UTC, ds-mwesener commented on COMPATIBILITY_MATRIX.md
> +| tractusx-connector   | 0.5.0   | 2023-10-26            |                        |
Same here - we do not maintain edc provider

2023-10-27 08:48 UTC, ds-mwesener commented on COMPATIBILITY_MATRIX.md
> +all versions are compatible
all versions are compatible are not correct. Please add the discovery service to trace-x like the other services and remove the section here.

2023-10-27 08:48 UTC, ds-mwesener commented on COMPATIBILITY_MATRIX.md
> +all versions are compatible
same for portal, sd-factory, wallet

2023-10-27 08:49 UTC, ds-mwesener requested changes
Hi @ds-jleyh please address my feedback. Thank you

2023-11-08 07:32 UTC, ds-jleyh commented on COMPATIBILITY_MATRIX.md
> +
It depends. I think it can be helpful e.g. if the date is 3 years old, this may be an indication that the information should be revised. On the other hand, we also have the version displayed, so perhaps it is unnecessary. What do you think?

2023-11-08 14:07 UTC, ds-mwesener commented on COMPATIBILITY_MATRIX.md
> +| Name of service      | Version | Comments               |
I think from trace-x perspective we do not need to have a version matrix for the edc or the registry. Please remove them.

2023-11-08 15:39 UTC, mkanal approved these changes

2023-11-08 15:39 UTC, mkanal commented on COMPATIBILITY_MATRIX.md
> +
I need the information to which  C-X release the release belongs to. 

# RELEASE 

## CATENA-X Release 23.9

### **(Release)** [4.0.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.0) | [Release Notes](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.0)  

| Name of service                  | Version | Comments   |
|----------------------------------|---------|------------|
| postgresql                       | 12.1.6  |            |
| postgresql alias: edc-postgresql | 12.1.6  |            |
| pgadmin4                         | 1.13.6  |            |
| irs-helm                         | 6.8.0   |            |
| tractusx-connector               | 0.5.0   |            |
| discovery service                | 0.1.0   |            |
| portal                           | ?       |            |
| SD-Factory                       | ?       |            |
| wallet                           | ?       |            |

### **(Hotfix)** [4.0.1](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.1) | [Release Notes](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.1)  

| Name of service                  | Version | Comments   |
|----------------------------------|---------|------------|
| postgresql                       | 12.1.6  |            |
| postgresql alias: edc-postgresql | 12.1.6  |            |
| pgadmin4                         | 1.13.6  |            |
| irs-helm                         | 6.8.0   |            |
| tractusx-connector               | 0.5.0   |            |
| discovery service                | 0.1.0   |            |
| portal                           | ?       |            |
| SD-Factory                       | ?       |            |
| wallet                           | ?       |            |

### **(Hotfix)** [4.0.2](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.2) | [Release Notes](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/4.0.2)  

| Name of service                  | Version | Comments   |
|----------------------------------|---------|------------|
| postgresql                       | 12.1.6  |            |
| postgresql alias: edc-postgresql | 12.1.6  |            |
| pgadmin4                         | 1.13.6  |            |
| irs-helm                         | 6.8.0   |            |
| tractusx-connector               | 0.5.0   |            |
| discovery service                | 0.1.0   |            |
| portal                           | ?       |            |
| SD-Factory                       | ?       |            |
| wallet                           | ?       |            |

## Release 23.12


### **(Hotfix)** [5.0.0](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.0.0) | [Release Notes](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.0.0)  

..... 

### **(Hotfix)** [5.0.1](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.0.1) | [Release Notes](https://github.com/eclipse-tractusx/item-relationship-service/releases/tag/5.0.1)  

..... 


## Dependencies
| Shared Service  | Link                                                                                         |  
|--|----------------------------------------------------------------------------------------------|
|tractusx-edc | [tractusx-edc](https://github.com/eclipse-tractusx/tractusx-edc)                                         | 
|sldt-digital-twin-registry| [sldt-digital-twin-registry](https://github.com/eclipse-tractusx/sldt-digital-twin-registry) |
|sldt-discovery-finder| [sldt-discovery-finder](https://github.com/eclipse-tractusx/sldt-discovery-finder)           | 
|sldt-semantic-hub | [sldt-semantic-hub](https://github.com/eclipse-tractusx/sldt-semantic-hub)                   |
|managed-identity-wallet | [managed-identity-wallet](https://github.com/eclipse-tractusx/managed-identity-wallet)       |

2023-11-09 09:22 UTC, ds-jleyh commented
@ds-mwesener I added the requested information as discussed :)

2023-11-09 10:21 UTC, ds-mwesener approved these changes

2023-11-09 10:21 UTC, merged