chore: TRACEFOSS-XXX update user manual
catenax-ng/tx-traceability-foss pull request #790
Opened 2023-11-23 10:18 UTC by ds-lcapellino

2023-11-23 12:29 UTC, ds-lcapellino commented
This Confluence page can be deleted: https://confluence.catena-x.net/display/BDPQ/2.+%28TRF%29+Code+Standards+-+Backend
It has been migrated into the repo after the merge.

2023-11-24 06:53 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +For local testing purposes, there is an additional configuration file called `+application-local.yml+`.
Hi @ds-lcapellino currently we do not have the local setup. Please remove this section. Thanks!

2023-11-24 06:54 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +
Please add: application-integration.yml is used as base for integration testing.

2023-11-24 06:58 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +
Implements a static mapper which provides a Domain to Response Mapping

2023-11-24 06:59 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +=== DTO (Data Transfer Object)
Please remove DTO as this concept is not used.

2023-11-24 07:00 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +* Responsible for transforming data objects (private) to data transfer objects (public)
Remove this line as the transformation is not done inside the facade

2023-11-24 07:00 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +* Returns a public object → Data Transfer Object
Remove this line. Is done inside controller

2023-11-24 07:01 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +=== Service
Rename to serviceImpl

2023-11-24 07:01 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +** Only if facade is not used will take care of transforming data objects (private) to data transfer objects (public)
Remove this line.

2023-11-24 07:02 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +* Can be implemented in a controller
Should only be implemented in a controller through an interface

2023-11-24 07:02 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +=== DAO (Data Access Object)
Concept not implemented. Please remove DAO completely

2023-11-24 07:04 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +=== Repository
Please change the full description of Repository

Represents an interface to the underlying repository implementation which uses then the spring repository.

2023-11-24 07:04 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +=== Domain Object (Entity Object?)
remove entity object

2023-11-24 07:04 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +* Includes relations to other JPA Entities
delete this line

2023-11-24 07:05 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +* Is well annotated to describe all aspects of the database model
delete this line.

2023-11-24 07:06 UTC, ds-mwesener commented on docs/src/docs/arc42/cross-cutting/development-concepts.adoc
> +=== Domain Object (Entity Object?)
Also change full description: 
Mapped from an entity or external data received
Will be used as working model until it will be final transformed to a response object or another domain which will be later on persited

2023-11-24 07:07 UTC, ds-mwesener requested changes
Hi @ds-lcapellino thanks for your work. Added some feedback.

2023-11-24 10:28 UTC, ds-mwesener approved these changes

2023-11-24 10:37 UTC, ds-mwesener approved these changes

2023-11-24 10:37 UTC, merged