chore:[TRACEFOSS-XXX] added erm
catenax-ng/tx-traceability-foss pull request #797
Opened 2023-11-27 10:38 UTC by ds-ashanmugavel

2023-11-27 12:55 UTC, hgo-ds requested changes

2023-11-27 12:55 UTC, hgo-ds commented on docs/src/uml-diagrams/arc42/cross-cutting/PUML_V1__base_sql_configuration.puml
> +  id_short : varchar(255)
**Suggestion:**

Would it help to name the `id`, and the `id_short` more clearly so that is documented what the 'id' is about.

```suggestion
  asset_as_built_child_id : varchar(255)
  asset_as_built_child_id_short : varchar(255)
```

This suggestion also applies to the other relationship tables `assets_as_built_parents` and `assets_as_planned_childs`.

2023-12-01 06:48 UTC, ds-mwesener commented on docs/src/uml-diagrams/arc42/cross-cutting/PUML_V1__base_sql_configuration.puml
> +  catenax_site_id : varchar(255)
Hi @hgo-ds thanks for the recommendation. As this should reflect the current situation we will not update the uml on this point but will follow up on the real code base and later on update the uml as well.

2023-12-01 06:57 UTC, ds-mwesener requested changes
Hi @ds-ashanmugavel please make sure that this entity relationship model will be added to the structure:
Cross-cutting concepts
First section should be new: Entity-Relationhip Model
Then your new model.
Next section will be then Domain concepts.

2023-12-01 06:58 UTC, ds-mwesener commented on docs/src/uml-diagrams/arc42/cross-cutting/PUML_V1__base_sql_configuration.puml
> +@startuml
Please give the file a proper naming.

2023-12-01 06:58 UTC, ds-mwesener commented on CHANGELOG.md
> +- Added an Entity Relationship Model (ERM) to visualize our tables and their relationships.
Add the info that it was added to the Architecture Documentation

2023-12-04 14:34 UTC, ds-mwesener commented
Please add a info that the asplanned currently does not have the database relation but leave the ERM as it is.

2023-12-05 06:28 UTC, ds-mwesener commented on CHANGELOG.md
>  - DEPENDENCIES_FRONTEND, SECURITY.md, NOTICE.md, LICENSE file to frontend docker image
Hi @ds-ashanmugavel please make sure to include the erm into the index.adoc (within docs/src/docs/arc42/cross-cutting/index.adoc

It should be the first point of the index:
- xref:entity-relationship-model.adoc[Entity Relationship Model]

2023-12-05 06:29 UTC, ds-mwesener requested changes
Please fix comment.

2023-12-05 08:33 UTC, ds-mwesener approved these changes

2023-12-05 08:34 UTC, merged