bug: 392 limit filter query parameters to 50
catenax-ng/tx-traceability-foss pull request #884
Opened 2024-01-10 08:05 UTC by ds-lcapellino

2024-01-11 10:27 UTC, ds-mwesener requested changes

2024-01-11 10:27 UTC, ds-mwesener commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/qualitynotification/alert/AlertControllerFilterIT.java
> +                .queryParam("filter", "bpn,STARTS_WITH,BPNL00000001OWN,OR").and()
Please create simple loop for the queryParams

2024-01-11 12:52 UTC, ds-lcapellino commented
New endpoints:
POST /api/investigations/filter
POST /api/alerts/filter

Request sample:
```json
{
    "pageAble": {
        "page": 0,
        "size": 10,
        "sort": [
            "description,ASC"
        ]
    },
    "searchCriteria": {
        "filter": [
            "channel,EQUAL,SENDER,AND"
        ]
    }
}
```

2024-01-12 14:06 UTC, ds-mwesener approved these changes

2024-01-12 14:06 UTC, merged