chore[xxx] updated error handling in publishAssets method
catenax-ng/tx-traceability-foss pull request #946
Opened 2024-01-25 09:29 UTC by ds-ashanmugavel

2024-01-25 10:07 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
> +            throw new AssetNotFoundException("Asset with ID " + assetBase.getId() + " is not in TRANSIENT state.");
Do not throw an AssetNotFoundException. Please use something like an PublishAssetException.

2024-01-25 10:12 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
> +    private static void checkImportState(AssetBase assetBase) {
As this is not only checking please rename method to: validTransientState

2024-01-25 10:13 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
> +                .peek(assetAsPlanned -> {
Why peek and not map?

2024-01-25 10:13 UTC, ds-mwesener requested changes
Please fix.

2024-01-26 06:52 UTC, ds-mwesener requested changes
Lets check together.

2024-02-01 15:09 UTC, ds-mwesener commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/importdata/ImportControllerIT.java
> +                .statusCode(500);
We dont want to have a 500.

2024-02-01 15:10 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
> +    private boolean validTransientState(AssetBase assetBase) {
Why using boolean when in false case an exception will be thrown. Could be a simple void method which throws if validation fails.

2024-02-02 12:48 UTC, ds-mwesener requested changes
Please fix.

2024-02-05 08:29 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
> +        assetIds.forEach(this::throwIfNotExists);
Please wrap assetIds like this: emptyIfNull(assetIds)

2024-02-05 08:30 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
> +        log.info("Updating status of asPlannedAssets.");
Might be better to log all in a line like it was before. Otherwise we will have tons of those entries in the log

2024-02-05 08:32 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
> +        log.info("Successfully set {} in status IN_SYNCHRONIZATION", assetBases.stream().map(AssetBase::getId).collect(Collectors.joining(", ")));
Here this log should be sufficient.

2024-02-05 08:32 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfig.java
> +        log.warn("handleAssetNotFoundException", exception);
Remove warning.  Normal case.

2024-02-05 08:33 UTC, ds-mwesener submitted a review, later dismissed
Please fix.

2024-02-05 08:42 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/common/config/ErrorHandlingConfig.java
> +        log.warn("handleAssetNotFoundException", exception);
All logs inside the @RestControllerAdvice are on WARN level. Shall we refactor all?

2024-02-05 08:47 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
> +        assetIds.forEach(this::throwIfNotExists);
assetIds should not be null, as configured in the Request class:
        @NotEmpty
        List<String> assetIds) {

2024-02-05 08:49 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
> +        log.info("Updating status of asPlannedAssets.");
This is only indicates which repository is updated, because there can be zero updates in case the status of one assets is not in state "TRANSIENT"

2024-02-05 08:51 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/importpoc/service/PublishServiceImpl.java
> +        log.info("Successfully set {} in status IN_SYNCHRONIZATION", assetBases.stream().map(AssetBase::getId).collect(Collectors.joining(", ")));
Here it is not clear, which repository was updated. This is also not logged in case one asset is not in state "TRANSIENT"

2024-02-05 09:48 UTC, ds-ext-sceronik approved these changes
lgtm

2024-02-05 10:30 UTC, merged