chore(concept): #521 revoked notification handling
catenax-ng/tx-traceability-foss pull request #953
Opened 2024-01-26 12:19 UTC by ds-crehm

##Description
Add concept for https://github.com/eclipse-tractusx/traceability-foss/issues/521

2024-01-29 11:54 UTC, mkanal requested changes
Hi Christian, 
great work. Please see my remarks inside this PR.

2024-01-29 11:54 UTC, mkanal commented on docs/concept/#521-revoked-notification-handling/#521-revoked-notification-handling.md
> +Policies are stored in the IRS. The IRS provides an API to fetch and verify policies.
```suggestion
Policies are stored in the IRS's PolicyStore. The IRS provides an PolicyStore API to create, fetch and verify policies.
```

2024-01-29 11:54 UTC, mkanal commented on docs/concept/#521-revoked-notification-handling/#521-revoked-notification-handling.md
> +2. The policy is valid (validUntil >= current DateTime) but the notification is **not** permitted to be sent.
Case 2 is not clear to me. There are two validity constraints, time based (policy expiration) and permission based (policy definition matched the policy of catalog offer)

2024-01-29 11:54 UTC, mkanal commented on docs/concept/#521-revoked-notification-handling/#521-revoked-notification-handling.md
> +When the notification is not sent because of a permission issue or an invalid policy, the user must be notified properly.
Permission issue in one constraint of an invalid policy 
invalid policy 
 - time based 
 - permission or constraint based

2024-01-29 11:54 UTC, mkanal commented on docs/concept/#521-revoked-notification-handling/#521-revoked-notification-handling.md
> +# NFR
```suggestion

```

2024-01-29 11:54 UTC, mkanal commented on docs/concept/#521-revoked-notification-handling/#521-revoked-notification-handling.md
> +# Out of scope
```suggestion

```

2024-01-29 11:54 UTC, mkanal commented on docs/concept/#521-revoked-notification-handling/#521-revoked-notification-handling.md
> +1. A pop-up must be shown to the user
```suggestion
1. An error toast message  must be shown to the user
```

2024-01-29 11:54 UTC, mkanal commented on docs/concept/#521-revoked-notification-handling/#521-revoked-notification-handling.md
> +2. The notification status must be changed to "Failed"
We have to think about a transient state model which extends the standardized notification model with additional states -. 

See https://eclipse-tractusx.github.io/traceability-foss/docs/user/user-manual.html Quality alert status this is standardized and could not be changed. There is no ERROR or FAILED state. We have to extend this official notification model with transient states which are only handled within the Trace-X application. Please provide a sample where FAILED will be inside the state diagram. Thanks

2024-01-29 15:51 UTC, mkanal requested changes

2024-01-29 15:51 UTC, mkanal commented on docs/concept/#521-revoked-notification-handling/#521-revoked-notification-handling.md
> +- Error text message informing the user of the exception
Toast messages

2024-01-29 15:51 UTC, mkanal commented on docs/concept/#521-revoked-notification-handling/#521-revoked-notification-handling.md
> +1. An error text message must be shown to the user
Toast message

2024-01-31 12:09 UTC, mkanal approved these changes
LGFM

2024-01-31 12:33 UTC, ds-mwesener approved these changes

2024-01-31 12:36 UTC, merged