Chore/xxx fixed publish documentation workflow
catenax-ng/tx-traceability-foss pull request #983
Opened 2024-02-14 13:54 UTC by ds-ashanmugavel

2024-02-19 11:09 UTC, ds-mwesener submitted a review, later dismissed

2024-02-19 11:10 UTC, ds-mwesener requested changes
Hi @ds-ashanmugavel currently the dependency check fails. Please fix that then we can merge your changes. Thank you!

2024-02-21 09:21 UTC, ds-lcapellino commented on CHANGELOG.md
> +- updated publish-documentation workflow with two new steps
Please move this changelog entry to the top, so it is listed below "UNRELEASED". This probably happened by merging the main into your branch

2024-02-21 09:51 UTC, ds-lcapellino approved these changes
LGTM

2024-02-21 09:52 UTC, merged