chore(concept): 436 intermediate status handling
catenax-ng/tx-traceability-foss pull request #985
Opened 2024-02-15 09:11 UTC by ds-crehm

Resolves https://github.com/eclipse-tractusx/traceability-foss/issues/436

2024-02-15 10:58 UTC, mkanal requested changes

2024-02-15 10:58 UTC, mkanal commented on docs/concept/#436-intermediate-status-handling/#436-intermediate-status-handling.md
> +| 1     | Notification is created. This can be done by the User directly or by forwarding/duplicating an existing notification.
No html tags inside md are allowed. Linter will cause errors

2024-02-15 10:58 UTC, mkanal commented on docs/concept/#436-intermediate-status-handling/#436-intermediate-status-handling.md
> +| 5.3.2 | The notification is duplicated. The duplicate is forwarded to a new receiver. The forwarded notification will use the same state machine. The receiver becomes sender for the forwarded notif
Please remark this as it shall not be  implemented right now.

2024-02-15 10:58 UTC, mkanal commented on docs/concept/#436-intermediate-status-handling/#436-intermediate-status-handling.md
> +Notification messages: https://github.com/eclipse-tractusx/traceability-foss/issues/423
IMHO this ticket is not very helpful - contains a lot of technical information. Try to link the docu https://eclipse-tractusx.github.io/traceability-foss/docs/arc42/full.html#_notifications if there is any sensful information in it or please create a ticket in inbox to provide the required documentation.

2024-02-15 11:16 UTC, ds-crehm commented on docs/concept/#436-intermediate-status-handling/#436-intermediate-status-handling.md
> +Notification messages: https://github.com/eclipse-tractusx/traceability-foss/issues/423
I removed the reference. There is a bit of information about the message history in the user manual. But I don't think this will help either.

2024-02-15 11:20 UTC, mkanal submitted a review, later dismissed
LGFM

2024-02-19 11:05 UTC, ds-mwesener requested changes
As Martin has reviewed your concept. Please add a changelog entry. Afterwards we can merge.

2024-02-20 07:46 UTC, ds-mwesener approved these changes

2024-02-20 08:14 UTC, merged