Feature/533 enable handling of tombstones in be
catenax-ng/tx-traceability-foss pull request #994
Opened 2024-02-19 13:57 UTC by ds-lcapellino

2024-02-19 14:32 UTC, ds-mwesener commented on tx-backend/src/main/resources/db/migration/V14__add_tombstone_to_assets.sql
> +    ADD COLUMN "tombstone" varchar NULL;
Might be better to limit the varchar?

2024-02-19 15:40 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/IrsService.java
> +import org.apache.logging.log4j.util.Strings;
We should not rely on logging lib for string operations.

2024-02-19 15:40 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/IrsService.java
> +                if (Strings.isNotBlank(assetBase.getTombstone())) {
Use apache commons

2024-02-19 15:41 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/IrsService.java
> +                    setTombstone(assetAsBuiltCallbackRepository, assetBase);
Please move the setTombstone to the corresponding if else construct.

2024-02-19 15:42 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/JobDetailResponse.java
> +        ObjectMapper objectMapper = new ObjectMapper();
Try to inject the existing objectmapper instead of using a new one.

2024-02-19 15:42 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/JobDetailResponse.java
> +        tombstones.forEach(tombstone -> {
Might be better as stream?

2024-02-19 15:45 UTC, ds-mwesener requested changes
Hi, please fix comments.

2024-02-19 15:54 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/IrsService.java
> +                    setTombstone(assetAsBuiltCallbackRepository, assetBase);
This is not possible, because in the tombstone information there is only the catenax-Id. However, there is no information about the BOM lifecycle

2024-02-19 16:27 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/model/response/JobDetailResponse.java
> +        ObjectMapper objectMapper = new ObjectMapper();
Instead of changing the datamodel to be a Map<String, String> tombstones, you could simply take the tombstones as they are coming in and perform the mapping in the next stage outside of that JsonCreator.

2024-02-21 09:47 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/domain/base/model/AssetBase.java
> +        if (Objects.equals(semanticDataModel, SERIALPART) || Objects.equals(semanticDataModel, BATCH) || Objects.equals(semanticDataModel, JUSTINSEQUENCE) || Objects.equals(semanticDataModel, TOMBSTO
Might be good to provide a method isAsBuilt within semanticDataModel based on the ENUM Type

2024-02-21 09:48 UTC, ds-mwesener commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/IrsService.java
> +            existingAsset.setTombstone(asset.getTombstone());
I did not check everything so far. What happens if asset does not exist with the tombstone.

2024-02-21 09:52 UTC, ds-mwesener commented on tx-backend/src/test/java/org/eclipse/tractusx/traceability/integration/assets/infrastructure/base/IrsCallbackControllerIT.java
> +//        String path = getClass().getResource("/testdata/importfiles/validImportFile.json").getFile();
Why is this code outcommented?

2024-02-21 10:11 UTC, ds-lcapellino commented on tx-backend/src/main/java/org/eclipse/tractusx/traceability/assets/infrastructure/base/irs/IrsService.java
> +            existingAsset.setTombstone(asset.getTombstone());
The existins asset in that case would come from the import file via data ingestion process. If there is no tombstone present, the publishing to the network was successful and the tombstone value would be null

2024-02-21 15:51 UTC, ds-mwesener approved these changes

2024-02-21 15:51 UTC, merged